#!/bin/sh

set -e

case "$1" in
    remove|upgrade|deconfigure)
        ALTNAME=flash-mozilla.so
        if dpkg-vendor --derives-from Ubuntu; then
            ALTNAME=mozilla-flashplugin
        fi
        update-alternatives --quiet --remove $ALTNAME \
		/usr/lib/lightspark/liblightsparkplugin.so
    ;;

    failed-upgrade)
    ;;

    *)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

#DEBHELPER#

exit 0


